ci: puppeteer's quirks on Github Actions DEV-270 (#141)
First error, solved by moving puppeteer's cache directory and caching it
on Github Actions:
```
Error: Could not find Chrome (ver. 115.0.5790.98). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /home/runner/.cache/puppeteer).
```

Second error, solved by passing `--no-sandbox` argument to puppeteer on
CI only:
```
Error: Failed to launch the browser process!
[5265:5265:0619/154251.293633:FATAL:zygote_host_impl_linux.cc(127)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

Depends on #142 to see the errors in the first place.